### ISSUE TITLE
Composer: ZF2 + PHPUnit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/zf2-app-skeleton#2]
Before I can start coding, I will define the basic requirements needed in the 
application. This will be the Zend Framework 2 (``~2.4.0``) and PHPUnit (``4.8.0``).

**Min. PHP-Requirments**  
PHP-Version above 5.4.0

**ZF2 LTS**  
The **long time support** for the Zend Framework ``~2.4.0``, **expires** in **2018**.
[http://framework.zend.com/long-term-support/](http://framework.zend.com/long-term-support/)

## Tasks

- [ ] Require ``zendframework/zendframework ~2.4.0`` in _composer.json_
- [ ] Require ``phpunit/phpunit 4.8.0`` in _composer.json_
- [ ] Run Composer installation
- [ ] Ignore files in _/vendor_ directory in _.gitignore_

_v.0.0.8-0002_
